version: "2.1"
orbs:
  cypress: cypress-io/cypress@3
workflows:
  test:
    jobs:
      - cypress/run:
          filters:
            branches:
              only:
                - main
          install-command: npm install
          post-install: npm test
